version: '3.3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: pokexpress-server
    container_name: pokexpress-server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file: ./server/.env
    networks:
      - pokexpress-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: pokexpress-client
    container_name: pokexpress-client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    env_file: ./client/.env
    networks:
      - pokexpress-network

networks:
  pokexpress-network:
    driver: bridge
