version: '3.3'

services:

  mongoexpress:
    image: mongo-express
    container_name: mern-mongo-express
    networks:
      - app-network
    links:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=mern
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
