version: '3.3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: pokexpress-server
    container_name: pokexpress-server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: pokexpress-client
    container_name: pokexpress-client
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - server
